/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
//    implementation("com.google.guava:guava:30.1.1-jre")

    implementation ("commons-codec:commons-codec:1.10")
    implementation ("org.apache.logging.log4j:log4j-core:2.17.1")

    implementation (files("../lib/ml/maxent.jar"))
    implementation (files("../lib/ml/minorthird.jar"))
    implementation (files("../lib/qa/javelin.jar"))
    implementation (files("../lib/nlp/jwnl.jar"))
    implementation (files("../lib/nlp/lingpipe.jar"))
    implementation (files("../lib/nlp/opennlp-tools.jar"))
    implementation (files("../lib/nlp/plingstemmer.jar"))
    implementation (files("../lib/nlp/snowball.jar"))
    implementation (files("../lib/nlp/stanford-ner.jar"))
    implementation (files("../lib/nlp/stanford-parser.jar"))
    implementation (files("../lib/nlp/stanford-postagger.jar"))
    implementation (files("../lib/search/bing-search-java-sdk.jar"))
    implementation (files("../lib/search/googleapi.jar"))
    implementation (files("../lib/search/indri.jar"))
    implementation (files("../lib/search/yahoosearch.jar"))
    implementation (files("../lib/util/commons-logging.jar"))
//    implementation (files("../lib/util/gson.jar"))
    implementation (files("../lib/util/htmlparser.jar"))
    implementation (files("../lib/util/trove.jar"))

}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.7.2")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.prlancas.App")
}
